coonutils: Co0nUtilZ.C_FTPClient Class Reference
Co0nUtilZ.C_FTPClient Class Reference
Diese Klasse ist ein FTP-Client, welcher es ermöglicht Dateien mit einem FTP-Server Auszutauschen Created: 08/2017 Author: D. Marx Project: https://github.com/derco0n/coonutils License: GPLv2 - Means, this is free software which comes without any warranty but can be used, modified and redistributed free of charge You should have received a copy of that license: If not look here: https://www.gnu.org/licenses/gpl-2.0.de.html
Public Member Functions
C_FTPClient (string adress, string user, string password)
Initialisiert eine neue Instanz der FTP Helper Klasse anhand von Standardwerten
C_FTPClient (string adress, UInt16 port, string user, string password, Boolean usetls=false, Boolean passive=true)
Initialisiert eine neue Instanz der FTP Helper Klasse anhand von gegebenen Werten
delegate void CompleteEventhandler ()
delegate void MultiLoadProgressEventHandler (object sender, ProgressEventArgs Args)
Ereignis: Dateiliste komplett empfangen
delegate void ErrorEventHandler (object sender, ErrorEventArgs Fehler)
bool CreateFolder (String Path)
Erstellt einen Ordner auf dem FTP-Server
bool CheckConnection ()
Überprüft ob eine Verbindung zum FTP Server besteht. Gibt bei Erfolg TRUE zurück
System.Threading.Thread DownloadMultipleFiles (List< String > RemoteFiles, String localfolder, bool removeFileAfterTransfer)
Lädt eine kompletten Ordner (nicht rekursiv) vom Server herunter. Die Aktion wird in einem neuen Thread ausgeführt. Gibt den Thread zurück.
System.Threading.Thread UploadMultipleFiles (string remoteFolder, FileInfo[] Filelist, bool removeFileAfterTransfer)
Lädt eine komplette Dateiliste hoch. Die Aktion wird in einem neuen Thread ausgeführt. Gibt den Thread zurück.
bool UploadFile (string remoteFolder, FileInfo fileInfo, bool keepalive=false)
Lädt eine Datei auf einen FTP Server hoch
bool PathExists (String FullServerPath)
Prüft ob ein Pfad auf dem Server existiert
String existingPath (String FullServerPath)
Gibt den auf dem Server existierenden Teil eines Pfads zurück
Boolean FileExists (string remoteFolder, string filename, bool keepalive=false)
Prüft ob eine angebende Datei im Zielordner existiert
List< string > GetFileList (string remoteFolder, bool keepalive=false)
Liefert eine Liste von Dateien zurück, die sich in einem bestimmten Verzeichnis auf dem Server befinden
List< string > GetFileList ()
Liefert eine Liste von Dateien/Ordnern zurück
bool DownloadFile (string RemoteFileFullPath, string dstLocalFolder, bool keepalive=false)
Lädt eine Datei vom FTP Server herunter
DateTime LastModifiedTime (string RemoteFileFullPath)
Ermittelt den Zeitpunkt an dem eine Remotedatei zuletzt verändert wurde.
void DeleteFile (String RemotefileFullPath, bool keepalive=false)
Löscht eine Datei vom FTP Server
void DeleteFile (FileInfo RemoteFilePath, bool keepalive=false)
Löscht eine Datei vom FTP Server
List< String > GetFileListByRegex (String srcdir, String regex)
Static Public Member Functions
static bool ServicePointManager_ServerCertificateValidationCallback (object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
Prüft ob ein Web-Zertifikat gültig ist.
Static Public Attributes
static int PAUSEMS = 2
static int CONNECTIONTIMEOUT = 3600000
static int BUFFERSIZE = 2048
Properties
Exception lastException [get]
Gibt die letzte Exception zurück
string Adress [get, set]
FTP-Server-Adresse
string User [get, set]
FTP-Benutzer
string Password [get, set]
FTP-Passwort
Boolean UsePassive [get, set]
FTP-Passive-Modus.
Boolean UseTLS [get, set]
FTP über TLS benutzen
Events
MultiLoadProgressEventHandler UploadProgressChanged
Ereignis: Uploadfortschritt hat sich geändert
CompleteEventhandler UploadComplete
Ereignis: Upload abgeschlossen
MultiLoadProgressEventHandler DownloadProgressChanged
Ereignis: Downloadfortschritt hat sich geändert
CompleteEventhandler DownloadComplete
Ereignis: Download abgeschlossen
ErrorEventHandler FileTransferError
Ereignis: Dateiübertragunsfehler
Detailed Description
Diese Klasse ist ein FTP-Client, welcher es ermöglicht Dateien mit einem FTP-Server Auszutauschen Created: 08/2017 Author: D. Marx Project: https://github.com/derco0n/coonutils License: GPLv2 - Means, this is free software which comes without any warranty but can be used, modified and redistributed free of charge You should have received a copy of that license: If not look here: https://www.gnu.org/licenses/gpl-2.0.de.html
Definition at line 24 of file C_FTPClient.cs.
Constructor & Destructor Documentation
C_FTPClient() [1/2]
Co0nUtilZ.C_FTPClient.C_FTPClient (string adress, string user, string password)
Initialisiert eine neue Instanz der FTP Helper Klasse anhand von Standardwerten
Parameters
adress Name oder IP Adresse des Servers
user Benutzername
password Passwort
Definition at line 102 of file C_FTPClient.cs.
References Co0nUtilZ.C_FTPClient.Adress, Co0nUtilZ.C_FTPClient.Password, and Co0nUtilZ.C_FTPClient.User.
C_FTPClient() [2/2]
Co0nUtilZ.C_FTPClient.C_FTPClient (string adress, UInt16 port, string user, string password, Boolean usetls = false, Boolean passive = true)
Initialisiert eine neue Instanz der FTP Helper Klasse anhand von gegebenen Werten
Parameters
adress Name oder IP Adresse des Servers
port TCP-port
user Benutzername
password Passwort
usetls Verschlüsselte Verbindung True/False
passive FTP-Passive-Mode True/False
Definition at line 119 of file C_FTPClient.cs.
References Co0nUtilZ.C_FTPClient.Adress, Co0nUtilZ.C_FTPClient.CompleteEventhandler(), Co0nUtilZ.C_FTPClient.ErrorEventHandler(), Co0nUtilZ.C_FTPClient.MultiLoadProgressEventHandler(), Co0nUtilZ.C_FTPClient.Password, and Co0nUtilZ.C_FTPClient.User.
Member Function Documentation
CheckConnection()
bool Co0nUtilZ.C_FTPClient.CheckConnection ()
Überprüft ob eine Verbindung zum FTP Server besteht. Gibt bei Erfolg TRUE zurück
Definition at line 217 of file C_FTPClient.cs.
References Co0nUtilZ.C_FTPClient.Adress, Co0nUtilZ.C_FTPClient.Password, and Co0nUtilZ.C_FTPClient.User.
CompleteEventhandler()
delegate void Co0nUtilZ.C_FTPClient.CompleteEventhandler ()
Referenced by Co0nUtilZ.C_FTPClient.C_FTPClient().
CreateFolder()
bool Co0nUtilZ.C_FTPClient.CreateFolder (String Path)
Erstellt einen Ordner auf dem FTP-Server
Parameters
Path Zielverzeichnis
Definition at line 177 of file C_FTPClient.cs.
References Co0nUtilZ.C_FTPClient.Adress, Co0nUtilZ.C_FTPClient.Password, and Co0nUtilZ.C_FTPClient.User.
DeleteFile() [1/2]
void Co0nUtilZ.C_FTPClient.DeleteFile (String RemotefileFullPath, bool keepalive = false)
Löscht eine Datei vom FTP Server
Parameters
remoteFolder Zielverzeichnis
RemotefileFullPath Datei
keepalive Verbindung zum Server anschließend geöffnet lassen?
Definition at line 1135 of file C_FTPClient.cs.
References Co0nUtilZ.C_FTPClient.Adress, Co0nUtilZ.C_FTPClient.CONNECTIONTIMEOUT, Co0nUtilZ.C_FTPClient.Password, and Co0nUtilZ.C_FTPClient.User.
Referenced by Co0nUtilZ.C_FTPClient.DeleteFile(), and Co0nUtilZ.C_FTPClient.DownloadMultipleFiles().
DeleteFile() [2/2]
void Co0nUtilZ.C_FTPClient.DeleteFile (FileInfo RemoteFilePath, bool keepalive = false)
Löscht eine Datei vom FTP Server
Parameters
RemoteFilePath Datei auf dem Server
keepalive Verbindung zum Server anschließend geöffnet lassen?
Definition at line 1165 of file C_FTPClient.cs.
References Co0nUtilZ.C_FTPClient.DeleteFile().
DownloadFile()
bool Co0nUtilZ.C_FTPClient.DownloadFile (string RemoteFileFullPath, string dstLocalFolder, bool keepalive = false)
Lädt eine Datei vom FTP Server herunter
Parameters
RemoteFileFullPath Kompletter Pfad (inklusive Dateiname) zur Quelldatei
dstLocalFolder Lokaler Zielordner in welchen die Datei kopiert werden soll
keepalive Nach Transfer die Verbindung zum Server geöffnet lassen?
Returns
Gibt bei Erfolg TRUE zurück.
Definition at line 993 of file C_FTPClient.cs.
References Co0nUtilZ.C_FTPClient.Adress, Co0nUtilZ.C_FTPClient.BUFFERSIZE, Co0nUtilZ.C_FTPClient.CONNECTIONTIMEOUT, Co0nUtilZ.C_FTPClient.FileTransferError, Co0nUtilZ.C_FTPClient.LastModifiedTime(), Co0nUtilZ.C_FTPClient.Password, and Co0nUtilZ.C_FTPClient.User.
Referenced by Co0nUtilZ.C_FTPClient.DownloadMultipleFiles().
DownloadMultipleFiles()
System.Threading.Thread Co0nUtilZ.C_FTPClient.DownloadMultipleFiles (List< String > RemoteFiles, String localfolder, bool removeFileAfterTransfer)
Lädt eine kompletten Ordner (nicht rekursiv) vom Server herunter. Die Aktion wird in einem neuen Thread ausgeführt. Gibt den Thread zurück.
Parameters
RemoteFiles Quellordner auf dem Server
localfolder Lokaler Zielordner
Definition at line 271 of file C_FTPClient.cs.
References Co0nUtilZ.C_FTPClient.DeleteFile(), Co0nUtilZ.C_FTPClient.DownloadComplete, Co0nUtilZ.C_FTPClient.DownloadFile(), Co0nUtilZ.C_FTPClient.DownloadProgressChanged, Co0nUtilZ.File, Co0nUtilZ.C_FTPClient.FileTransferError, Co0nUtilZ.C_FTPClient.PathExists(), Co0nUtilZ.C_FTPClient.UploadComplete, Co0nUtilZ.C_FTPClient.UploadFile(), and Co0nUtilZ.C_FTPClient.UploadProgressChanged.
ErrorEventHandler()
delegate void Co0nUtilZ.C_FTPClient.ErrorEventHandler (object sender, ErrorEventArgs Fehler)
Referenced by Co0nUtilZ.C_FTPClient.C_FTPClient().
existingPath()
String Co0nUtilZ.C_FTPClient.existingPath (String FullServerPath)
Gibt den auf dem Server existierenden Teil eines Pfads zurück
Parameters
FullServerPath Kopletter Pfad (inklusive Server) zum Zielordner
Returns
Gibt den existierenden Teilpfad zurück
Definition at line 813 of file C_FTPClient.cs.
References Co0nUtilZ.C_FTPClient.GetFileList().
Referenced by Co0nUtilZ.C_FTPClient.PathExists().
FileExists()
Boolean Co0nUtilZ.C_FTPClient.FileExists (string remoteFolder, string filename, bool keepalive = false)
Prüft ob eine angebende Datei im Zielordner existiert
Parameters
remoteFolder Zielordner auf dem Server
filename Zu überprüfender Dateiname
keepalive Verbind nach Aufruf aktiv halten
Returns
TRUE wenn die Datei gefunden wurde, ansonsten FALSE
Definition at line 874 of file C_FTPClient.cs.
References Co0nUtilZ.C_FTPClient.GetFileList().
GetFileList() [1/2]
List<string> Co0nUtilZ.C_FTPClient.GetFileList (string remoteFolder, bool keepalive = false)
Liefert eine Liste von Dateien zurück, die sich in einem bestimmten Verzeichnis auf dem Server befinden
Parameters
remoteFolder Zielordner auf dem Server
keepalive Verbindung anschließend geöffnet lassen?
Returns
Gibt eine Liste mit gefundenen Dateien zurück
Definition at line 895 of file C_FTPClient.cs.
References Co0nUtilZ.C_FTPClient.Adress, Co0nUtilZ.C_FTPClient.CONNECTIONTIMEOUT, Co0nUtilZ.C_FTPClient.Password, and Co0nUtilZ.C_FTPClient.User.
GetFileList() [2/2]
List<string> Co0nUtilZ.C_FTPClient.GetFileList ()
Liefert eine Liste von Dateien/Ordnern zurück
Returns
Gibt eine Liste aller Dateien und Ordner zurück
Definition at line 981 of file C_FTPClient.cs.
Referenced by Co0nUtilZ.C_FTPClient.existingPath(), Co0nUtilZ.C_FTPClient.FileExists(), Co0nUtilZ.C_FTPClient.GetFileListByRegex(), and Co0nUtilZ.C_FTPClient.PathExists().
GetFileListByRegex()
List<String> Co0nUtilZ.C_FTPClient.GetFileListByRegex (String srcdir, String regex)
Definition at line 1171 of file C_FTPClient.cs.
References Co0nUtilZ.C_RegExHelper.FilterStringListByRegex(), and Co0nUtilZ.C_FTPClient.GetFileList().
LastModifiedTime()
DateTime Co0nUtilZ.C_FTPClient.LastModifiedTime (string RemoteFileFullPath)
Ermittelt den Zeitpunkt an dem eine Remotedatei zuletzt verändert wurde.
Parameters
RemoteFileFullPath
Returns
Definition at line 1099 of file C_FTPClient.cs.
References Co0nUtilZ.C_FTPClient.Adress, Co0nUtilZ.C_FTPClient.CONNECTIONTIMEOUT, Co0nUtilZ.C_FTPClient.Password, and Co0nUtilZ.C_FTPClient.User.
Referenced by Co0nUtilZ.C_FTPClient.DownloadFile().
MultiLoadProgressEventHandler()
delegate void Co0nUtilZ.C_FTPClient.MultiLoadProgressEventHandler (object sender, ProgressEventArgs Args)
Ereignis: Dateiliste komplett empfangen
Referenced by Co0nUtilZ.C_FTPClient.C_FTPClient().
PathExists()
bool Co0nUtilZ.C_FTPClient.PathExists (String FullServerPath)
Prüft ob ein Pfad auf dem Server existiert
Parameters
FullServerPath Kopletter Pfad (inklusive Server) zum Zielordner
Returns
Gibt True zurück, wenn der Ordner existiert.
Definition at line 775 of file C_FTPClient.cs.
References Co0nUtilZ.C_FTPClient.existingPath(), and Co0nUtilZ.C_FTPClient.GetFileList().
Referenced by Co0nUtilZ.C_FTPClient.DownloadMultipleFiles().
ServicePointManager_ServerCertificateValidationCallback()
static bool Co0nUtilZ.C_FTPClient.ServicePointManager_ServerCertificateValidationCallback (object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) static
Prüft ob ein Web-Zertifikat gültig ist.
Parameters
sender
certificate
chain
sslPolicyErrors
Returns
Definition at line 1186 of file C_FTPClient.cs.
UploadFile()
bool Co0nUtilZ.C_FTPClient.UploadFile (string remoteFolder, FileInfo fileInfo, bool keepalive = false)
Lädt eine Datei auf einen FTP Server hoch
Parameters
remoteFolder Zielverzeichnis
fileInfo Quelldatei
keepalive Verbindung nach Transfer geöffnet lassen?
Returns
Definition at line 670 of file C_FTPClient.cs.
References Co0nUtilZ.C_FTPClient.Adress, Co0nUtilZ.C_FTPClient.BUFFERSIZE, Co0nUtilZ.C_FTPClient.CONNECTIONTIMEOUT, Co0nUtilZ.File, Co0nUtilZ.C_FTPClient.Password, and Co0nUtilZ.C_FTPClient.User.
Referenced by Co0nUtilZ.C_FTPClient.DownloadMultipleFiles().
UploadMultipleFiles()
System.Threading.Thread Co0nUtilZ.C_FTPClient.UploadMultipleFiles (string remoteFolder, FileInfo [] Filelist, bool removeFileAfterTransfer)
Lädt eine komplette Dateiliste hoch. Die Aktion wird in einem neuen Thread ausgeführt. Gibt den Thread zurück.
Parameters
remoteFolder Zielordner auf dem Server
Filelist Array mit Quelldateien
Returns
Definition at line 603 of file C_FTPClient.cs.
Member Data Documentation
BUFFERSIZE
int Co0nUtilZ.C_FTPClient.BUFFERSIZE = 2048 static
Definition at line 28 of file C_FTPClient.cs.
Referenced by Co0nUtilZ.C_FTPClient.DownloadFile(), and Co0nUtilZ.C_FTPClient.UploadFile().
CONNECTIONTIMEOUT
int Co0nUtilZ.C_FTPClient.CONNECTIONTIMEOUT = 3600000 static
Definition at line 27 of file C_FTPClient.cs.
Referenced by Co0nUtilZ.C_FTPClient.DeleteFile(), Co0nUtilZ.C_FTPClient.DownloadFile(), Co0nUtilZ.C_FTPClient.GetFileList(), Co0nUtilZ.C_FTPClient.LastModifiedTime(), and Co0nUtilZ.C_FTPClient.UploadFile().
PAUSEMS
int Co0nUtilZ.C_FTPClient.PAUSEMS = 2 static
Definition at line 26 of file C_FTPClient.cs.
Property Documentation
Adress
string Co0nUtilZ.C_FTPClient.Adress get set
FTP-Server-Adresse
Definition at line 48 of file C_FTPClient.cs.
Referenced by Co0nUtilZ.C_FTPClient.C_FTPClient(), Co0nUtilZ.C_FTPClient.CheckConnection(), Co0nUtilZ.C_FTPClient.CreateFolder(), Co0nUtilZ.C_FTPClient.DeleteFile(), Co0nUtilZ.C_FTPClient.DownloadFile(), Co0nUtilZ.C_FTPClient.GetFileList(), Co0nUtilZ.C_FTPClient.LastModifiedTime(), and Co0nUtilZ.C_FTPClient.UploadFile().
lastException
Exception Co0nUtilZ.C_FTPClient.lastException get
Gibt die letzte Exception zurück
Definition at line 38 of file C_FTPClient.cs.
Password
string Co0nUtilZ.C_FTPClient.Password get set
FTP-Passwort
Definition at line 58 of file C_FTPClient.cs.
Referenced by Co0nUtilZ.C_FTPClient.C_FTPClient(), Co0nUtilZ.C_FTPClient.CheckConnection(), Co0nUtilZ.C_FTPClient.CreateFolder(), Co0nUtilZ.C_FTPClient.DeleteFile(), Co0nUtilZ.C_FTPClient.DownloadFile(), Co0nUtilZ.C_FTPClient.GetFileList(), Co0nUtilZ.C_FTPClient.LastModifiedTime(), and Co0nUtilZ.C_FTPClient.UploadFile().
UsePassive
Boolean Co0nUtilZ.C_FTPClient.UsePassive get set
FTP-Passive-Modus.
Definition at line 64 of file C_FTPClient.cs.
User
string Co0nUtilZ.C_FTPClient.User get set
FTP-Benutzer
Definition at line 53 of file C_FTPClient.cs.
Referenced by Co0nUtilZ.C_FTPClient.C_FTPClient(), Co0nUtilZ.C_FTPClient.CheckConnection(), Co0nUtilZ.C_FTPClient.CreateFolder(), Co0nUtilZ.C_FTPClient.DeleteFile(), Co0nUtilZ.C_FTPClient.DownloadFile(), Co0nUtilZ.C_FTPClient.GetFileList(), Co0nUtilZ.C_FTPClient.LastModifiedTime(), and Co0nUtilZ.C_FTPClient.UploadFile().
UseTLS
Boolean Co0nUtilZ.C_FTPClient.UseTLS get set
FTP über TLS benutzen
Definition at line 79 of file C_FTPClient.cs.
Event Documentation
DownloadComplete
CompleteEventhandler Co0nUtilZ.C_FTPClient.DownloadComplete
Ereignis: Download abgeschlossen
Definition at line 162 of file C_FTPClient.cs.
Referenced by Co0nUtilZ.C_FTPClient.DownloadMultipleFiles().
DownloadProgressChanged
MultiLoadProgressEventHandler Co0nUtilZ.C_FTPClient.DownloadProgressChanged
Ereignis: Downloadfortschritt hat sich geändert
Definition at line 157 of file C_FTPClient.cs.
Referenced by Co0nUtilZ.C_FTPClient.DownloadMultipleFiles().
FileTransferError
ErrorEventHandler Co0nUtilZ.C_FTPClient.FileTransferError
Ereignis: Dateiübertragunsfehler
Definition at line 167 of file C_FTPClient.cs.
Referenced by Co0nUtilZ.C_FTPClient.DownloadFile(), and Co0nUtilZ.C_FTPClient.DownloadMultipleFiles().
UploadComplete
CompleteEventhandler Co0nUtilZ.C_FTPClient.UploadComplete
Ereignis: Upload abgeschlossen
Definition at line 152 of file C_FTPClient.cs.
Referenced by Co0nUtilZ.C_FTPClient.DownloadMultipleFiles().
UploadProgressChanged
MultiLoadProgressEventHandler Co0nUtilZ.C_FTPClient.UploadProgressChanged
Ereignis: Uploadfortschritt hat sich geändert
Definition at line 147 of file C_FTPClient.cs.
Referenced by Co0nUtilZ.C_FTPClient.DownloadMultipleFiles().
The documentation for this class was generated from the following file:
Co0nUtilZ/C_FTPClient.cs