coonutils: Co0nUtilZ.C_NetworkConnection Class Reference
Co0nUtilZ.C_NetworkConnection Class Reference
This Class connects to network shares (samba/cifs) Created: 08/2017 Author: D. Marx Project: https://github.com/derco0n/coonutils License: GPLv2 - Means, this is free software which comes without any warranty but can be used, modified and redistributed free of charge You should have received a copy of that license: If not look here: https://www.gnu.org/licenses/gpl-2.0.de.html
Public Member Functions
delegate void ErrorEventHandler (object sender, ErrorEventArgs Fehler)
void InitializeErrorhints ()
C_NetworkConnection (string networkName, NetworkCredential credentials)
Diese Klasse stellt den Zugriff auf eine Netzwerkfreigabe mittels API-Zugriffen her
String Connect ()
Verbindet die zuvor definierte Netzwerkfreigabe. Im Fehlerfall ein das Event NetworkError ausgelöst.
void Dispose ()
Public Attributes
Dictionary< String, String > Errorhints = new Dictionary<string, string>()
Protected Member Functions
virtual void Dispose (bool disposing)
Events
ErrorEventHandler NetworkError
Detailed Description
This Class connects to network shares (samba/cifs) Created: 08/2017 Author: D. Marx Project: https://github.com/derco0n/coonutils License: GPLv2 - Means, this is free software which comes without any warranty but can be used, modified and redistributed free of charge You should have received a copy of that license: If not look here: https://www.gnu.org/licenses/gpl-2.0.de.html
Definition at line 21 of file C_NetworkConnection.cs.
Constructor & Destructor Documentation
C_NetworkConnection()
Co0nUtilZ.C_NetworkConnection.C_NetworkConnection (string networkName, NetworkCredential credentials)
Diese Klasse stellt den Zugriff auf eine Netzwerkfreigabe mittels API-Zugriffen her
Parameters
networkName Kompletter Netzwerkpfad (\Server)
credentials Zugangsdaten zur Freigabe
Definition at line 48 of file C_NetworkConnection.cs.
Referenced by Co0nUtilZ.C_NetworkConnection.InitializeErrorhints().
Member Function Documentation
Connect()
String Co0nUtilZ.C_NetworkConnection.Connect ()
Verbindet die zuvor definierte Netzwerkfreigabe. Im Fehlerfall ein das Event NetworkError ausgelöst.
Returns
Ergebnis des Verbindugsversuchs
Definition at line 72 of file C_NetworkConnection.cs.
Referenced by Co0nUtilZ.C_CIFSClient.CopyFileFromCIFS(), Co0nUtilZ.C_CIFSClient.CopyFileToCIFS(), Co0nUtilZ.C_CIFSClient.getFolderInfo(), Co0nUtilZ.C_NetworkConnection.InitializeErrorhints(), Co0nUtilZ.C_CIFSClient.isYoungestFile(), Co0nUtilZ.C_CIFSClient.listFiles(), Co0nUtilZ.C_CIFSClient.listFolders(), Co0nUtilZ.C_CIFSClient.MoveFileFromCIFS(), Co0nUtilZ.C_CIFSClient.MoveFileToCIFS(), Co0nUtilZ.C_CIFSClient.TestConnection(), and Co0nUtilZ.C_CIFSClient.youngestFile().
Dispose() [1/2]
void Co0nUtilZ.C_NetworkConnection.Dispose ()
Definition at line 111 of file C_NetworkConnection.cs.
Referenced by Co0nUtilZ.C_NetworkConnection.InitializeErrorhints().
Dispose() [2/2]
virtual void Co0nUtilZ.C_NetworkConnection.Dispose (bool disposing) protected virtual
Definition at line 117 of file C_NetworkConnection.cs.
ErrorEventHandler()
delegate void Co0nUtilZ.C_NetworkConnection.ErrorEventHandler (object sender, ErrorEventArgs Fehler)
InitializeErrorhints()
void Co0nUtilZ.C_NetworkConnection.InitializeErrorhints ()
Definition at line 37 of file C_NetworkConnection.cs.
References Co0nUtilZ.C_NetworkConnection.C_NetworkConnection(), Co0nUtilZ.C_NetworkConnection.Connect(), Co0nUtilZ.C_NetworkConnection.Dispose(), and Co0nUtilZ.C_NetworkConnection.NetworkError.
Member Data Documentation
Errorhints
Dictionary<String, String> Co0nUtilZ.C_NetworkConnection.Errorhints = new Dictionary<string, string>()
Definition at line 35 of file C_NetworkConnection.cs.
Event Documentation
NetworkError
ErrorEventHandler Co0nUtilZ.C_NetworkConnection.NetworkError
Definition at line 31 of file C_NetworkConnection.cs.
Referenced by Co0nUtilZ.C_CIFSClient.CopyFileFromCIFS(), Co0nUtilZ.C_CIFSClient.CopyFileToCIFS(), Co0nUtilZ.C_CIFSClient.getFolderInfo(), Co0nUtilZ.C_NetworkConnection.InitializeErrorhints(), Co0nUtilZ.C_CIFSClient.isYoungestFile(), Co0nUtilZ.C_CIFSClient.listFiles(), Co0nUtilZ.C_CIFSClient.listFolders(), Co0nUtilZ.C_CIFSClient.MoveFileFromCIFS(), Co0nUtilZ.C_CIFSClient.MoveFileToCIFS(), Co0nUtilZ.C_CIFSClient.TestConnection(), and Co0nUtilZ.C_CIFSClient.youngestFile().
The documentation for this class was generated from the following file:
Co0nUtilZ/C_NetworkConnection.cs