coonutils: Co0nUtilZ.C_LoggingHelper Class Reference
Co0nUtilZ.C_LoggingHelper Class Reference
This class helps logging to Windows Eventlog Created: 09/2017 Author: D. Marx Project: https://github.com/derco0n/coonutils License: GPLv2 - Means, this is free software which comes without any warranty but can be used, modified and redistributed free of charge You should have received a copy of that license: If not look here: https://www.gnu.org/licenses/gpl-2.0.de.html
Public Member Functions
C_LoggingHelper (String Sourcename, String MsgPrefix, String Log="Application")
Instanziert ein neues Objekt einer Helferklasse zum Logging im Windows-Ereignisprotokoll
bool Log (String Message, EventLogEntryType Type, Int32 Messagenumber)
Protokolliert eine Meldung im Windows Ereignisprotokoll
bool LogError (String Message, Int32 Messagenumber)
Protokolliert eine Fehlermeldung im Windows Ereignisprotokoll
bool LogWarn (String Message, Int32 Messagenumber)
Protokolliert eine Warnmeldung im Windows Ereignisprotokoll
bool LogInfo (String Message, Int32 Messagenumber)
Protokolliert eine Infomeldung im Windows Ereignisprotokoll
Static Public Attributes
static String LOG_APPLICATION = "Application"
static String LOG_SYSTEM = "System"
static EventLogEntryType TYPE_INFO = EventLogEntryType.Information
static EventLogEntryType TYPE_WARN = EventLogEntryType.Warning
static EventLogEntryType TYPE_ERROR = EventLogEntryType.Error
static int MESSAGE_MAXLENGTH = 32760
Properties
String Logsourcename [get]
Name der Loggingquelle
String Logname [get]
Name des Logs (Application/System)
String MsgPrefix [get, set]
Prefix welches Nachrichten vorangestellt werden soll
Detailed Description
This class helps logging to Windows Eventlog Created: 09/2017 Author: D. Marx Project: https://github.com/derco0n/coonutils License: GPLv2 - Means, this is free software which comes without any warranty but can be used, modified and redistributed free of charge You should have received a copy of that license: If not look here: https://www.gnu.org/licenses/gpl-2.0.de.html
Definition at line 20 of file C_LoggingHelper.cs.
Constructor & Destructor Documentation
C_LoggingHelper()
Co0nUtilZ.C_LoggingHelper.C_LoggingHelper (String Sourcename, String MsgPrefix, String Log = "Application")
Instanziert ein neues Objekt einer Helferklasse zum Logging im Windows-Ereignisprotokoll
Parameters
Sourcename Name der Loggingquelle (Frei wählbarer Name)
Log Welches Log soll verwendet werden? Std.: Application
Definition at line 94 of file C_LoggingHelper.cs.
Member Function Documentation
Log()
bool Co0nUtilZ.C_LoggingHelper.Log (String Message, EventLogEntryType Type, Int32 Messagenumber)
Protokolliert eine Meldung im Windows Ereignisprotokoll
Parameters
Message Inhalt der Nachricht
Type Art der Nachricht (Info, Warning oder Error)
Messagenumber Eindeutige Nummer der Meldung
Returns
Gibt im Fehlerfall FALSE zurück
Definition at line 120 of file C_LoggingHelper.cs.
References Co0nUtilZ.C_LoggingHelper.MESSAGE_MAXLENGTH, and Co0nUtilZ.C_RegExHelper.SplitString().
Referenced by Co0nUtilZ.C_LoggingHelper.LogError(), Co0nUtilZ.C_LoggingHelper.LogInfo(), and Co0nUtilZ.C_LoggingHelper.LogWarn().
LogError()
bool Co0nUtilZ.C_LoggingHelper.LogError (String Message, Int32 Messagenumber)
Protokolliert eine Fehlermeldung im Windows Ereignisprotokoll
Parameters
Message >Inhalt der Nachricht
Messagenumber Eindeutige Nummer der Meldung
Returns
Gibt im Fehlerfall FALSE zurück
Definition at line 159 of file C_LoggingHelper.cs.
References Co0nUtilZ.C_LoggingHelper.Log(), and Co0nUtilZ.C_LoggingHelper.TYPE_ERROR.
LogInfo()
bool Co0nUtilZ.C_LoggingHelper.LogInfo (String Message, Int32 Messagenumber)
Protokolliert eine Infomeldung im Windows Ereignisprotokoll
Parameters
Message >Inhalt der Nachricht
Messagenumber Eindeutige Nummer der Meldung
Returns
Gibt im Fehlerfall FALSE zurück
Definition at line 181 of file C_LoggingHelper.cs.
References Co0nUtilZ.C_LoggingHelper.Log(), and Co0nUtilZ.C_LoggingHelper.TYPE_INFO.
LogWarn()
bool Co0nUtilZ.C_LoggingHelper.LogWarn (String Message, Int32 Messagenumber)
Protokolliert eine Warnmeldung im Windows Ereignisprotokoll
Parameters
Message >Inhalt der Nachricht
Messagenumber Eindeutige Nummer der Meldung
Returns
Gibt im Fehlerfall FALSE zurück
Definition at line 170 of file C_LoggingHelper.cs.
References Co0nUtilZ.C_LoggingHelper.Log(), and Co0nUtilZ.C_LoggingHelper.TYPE_WARN.
Member Data Documentation
LOG_APPLICATION
String Co0nUtilZ.C_LoggingHelper.LOG_APPLICATION = "Application" static
Definition at line 24 of file C_LoggingHelper.cs.
LOG_SYSTEM
String Co0nUtilZ.C_LoggingHelper.LOG_SYSTEM = "System" static
Definition at line 25 of file C_LoggingHelper.cs.
MESSAGE_MAXLENGTH
int Co0nUtilZ.C_LoggingHelper.MESSAGE_MAXLENGTH = 32760 static
Definition at line 29 of file C_LoggingHelper.cs.
Referenced by Co0nUtilZ.C_LoggingHelper.Log().
TYPE_ERROR
EventLogEntryType Co0nUtilZ.C_LoggingHelper.TYPE_ERROR = EventLogEntryType.Error static
Definition at line 28 of file C_LoggingHelper.cs.
Referenced by Co0nUtilZ.C_LoggingHelper.LogError().
TYPE_INFO
EventLogEntryType Co0nUtilZ.C_LoggingHelper.TYPE_INFO = EventLogEntryType.Information static
Definition at line 26 of file C_LoggingHelper.cs.
Referenced by Co0nUtilZ.C_LoggingHelper.LogInfo().
TYPE_WARN
EventLogEntryType Co0nUtilZ.C_LoggingHelper.TYPE_WARN = EventLogEntryType.Warning static
Definition at line 27 of file C_LoggingHelper.cs.
Referenced by Co0nUtilZ.C_LoggingHelper.LogWarn().
Property Documentation
Logname
String Co0nUtilZ.C_LoggingHelper.Logname get
Name des Logs (Application/System)
Definition at line 58 of file C_LoggingHelper.cs.
Logsourcename
String Co0nUtilZ.C_LoggingHelper.Logsourcename get
Name der Loggingquelle
Definition at line 47 of file C_LoggingHelper.cs.
MsgPrefix
String Co0nUtilZ.C_LoggingHelper.MsgPrefix get set
Prefix welches Nachrichten vorangestellt werden soll
Definition at line 69 of file C_LoggingHelper.cs.
The documentation for this class was generated from the following file:
Co0nUtilZ/C_LoggingHelper.cs