coonutils: Co0nUtilZ.C_Crypto Class Reference
Co0nUtilZ.C_Crypto Class Reference
Encryptionhelper-Class. Created: 10/2017 Author: D. Marx Project: https://github.com/derco0n/coonutils License: GPLv2 - Means, this is free software which comes without any warranty but can be used, modified and redistributed free of charge You should have received a copy of that license: If not look here: https://www.gnu.org/licenses/gpl-2.0.de.html
Public Member Functions
byte [] AES_Encrypt (byte[] bytesToBeEncrypted, byte[] passwordBytes, byte[] saltBytes)
Verschlüsselt (mit AES) ein Bytearray
byte [] AES_Decrypt (byte[] bytesToBeDecrypted, byte[] passwordBytes, byte[] saltBytes)
Entschlüsselt ein mit AES verschlüsseltes ByteArray
string EncryptText (string input, string password, byte[] saltBytes, string error="Fehler beim Verschlüsseln.")
Verschlüsselt einen String
string DecryptText (string input, string password, byte[] saltBytes, string error="Fehler beim Entschlüsseln")
Entschlüsselt einen String
Detailed Description
Encryptionhelper-Class. Created: 10/2017 Author: D. Marx Project: https://github.com/derco0n/coonutils License: GPLv2 - Means, this is free software which comes without any warranty but can be used, modified and redistributed free of charge You should have received a copy of that license: If not look here: https://www.gnu.org/licenses/gpl-2.0.de.html
Definition at line 21 of file C_Crypto.cs.
Member Function Documentation
AES_Decrypt()
byte [] Co0nUtilZ.C_Crypto.AES_Decrypt (byte [] bytesToBeDecrypted, byte [] passwordBytes, byte [] saltBytes)
Entschlüsselt ein mit AES verschlüsseltes ByteArray
Parameters
bytesToBeDecrypted Eingabe
passwordBytes Entschlüsselungskey
saltBytes Salt als Bytearray mit mindestens 8 Werten
Returns
Entschlüsseltes Bytearray
Definition at line 73 of file C_Crypto.cs.
Referenced by Co0nUtilZ.C_Crypto.DecryptText().
AES_Encrypt()
byte [] Co0nUtilZ.C_Crypto.AES_Encrypt (byte [] bytesToBeEncrypted, byte [] passwordBytes, byte [] saltBytes)
Verschlüsselt (mit AES) ein Bytearray
Parameters
bytesToBeEncrypted Eingabe
passwordBytes Schlüssel
saltBytes Salt als Bytearray mit mindestens 8 Werten
Returns
verschlüsselte Ausgabe
Definition at line 30 of file C_Crypto.cs.
Referenced by Co0nUtilZ.C_Crypto.EncryptText().
DecryptText()
string Co0nUtilZ.C_Crypto.DecryptText (string input, string password, byte [] saltBytes, string error = "Fehler beim Entschlüsseln")
Entschlüsselt einen String
Parameters
input Verschlüsselter String
password Passwort zum Entschlüsseln
saltBytes Salt als Bytearray mit mindestens 8 Werten
Returns
Entschlüsselter String
Definition at line 149 of file C_Crypto.cs.
References Co0nUtilZ.C_Crypto.AES_Decrypt().
EncryptText()
string Co0nUtilZ.C_Crypto.EncryptText (string input, string password, byte [] saltBytes, string error = "Fehler beim Verschlüsseln.")
Verschlüsselt einen String
Parameters
input String zum Verschlüsseln
password Verschlüsselungspasswort
saltBytes Salt als Bytearray mit mindestens 8 Werten
Returns
Verschlüsselter String
Definition at line 117 of file C_Crypto.cs.
References Co0nUtilZ.C_Crypto.AES_Encrypt().
The documentation for this class was generated from the following file:
Co0nUtilZ/C_Crypto.cs