coonutils: Co0nUtilZ.C_RegExHelper Class Reference
Co0nUtilZ.C_RegExHelper Class Reference
Helperclass for regular expressions Created: 12.10.2017 Author: D. Marx Project: https://github.com/derco0n/coonutils License: GPLv2 - Means, this is free software which comes without any warranty but can be used, modified and redistributed free of charge You should have received a copy of that license: If not look here: https://www.gnu.org/licenses/gpl-2.0.de.html
Public Member Functions
List< String > SplitString (String str, int chunks)
List< String > FilterStringListByRegex (List< String > input, String RegexFilter)
Filtert aus einer Liste mit Strings, die Einträge heraus die mit dem angegebenen Filter übereinstimmen.
bool RegExFilterisGood (String RegexFilter)
Testet ob ein RegEx-Filter gültig ist
int CheckRegEx (String Testword, String RegexFilter)
Prüft ob eine Zeichenfolge vom Filter erfasst wird.
Detailed Description
Helperclass for regular expressions Created: 12.10.2017 Author: D. Marx Project: https://github.com/derco0n/coonutils License: GPLv2 - Means, this is free software which comes without any warranty but can be used, modified and redistributed free of charge You should have received a copy of that license: If not look here: https://www.gnu.org/licenses/gpl-2.0.de.html
Definition at line 20 of file C_RegExHelper.cs.
Member Function Documentation
CheckRegEx()
int Co0nUtilZ.C_RegExHelper.CheckRegEx (String Testword, String RegexFilter)
Prüft ob eine Zeichenfolge vom Filter erfasst wird.
Parameters
Testword Zu testende Zeichenfolge
RegexFilter Reg.-Ex-Filter
Returns
0=Übereinstimmung,1=Keine Übereinstimmung,2=Filter ungültig,3=Testword oder RegexFilter nicht gesetzt.
Definition at line 93 of file C_RegExHelper.cs.
References Co0nUtilZ.C_RegExHelper.RegExFilterisGood().
Referenced by Co0nUtilZ.C_RegExHelper.FilterStringListByRegex().
FilterStringListByRegex()
List<String> Co0nUtilZ.C_RegExHelper.FilterStringListByRegex (List< String > input, String RegexFilter)
Filtert aus einer Liste mit Strings, die Einträge heraus die mit dem angegebenen Filter übereinstimmen.
Parameters
input Eingabeliste
RegexFilter Filter
Returns
Liste mit Einträgen die mit dem Filter übereinstimmen
Definition at line 46 of file C_RegExHelper.cs.
References Co0nUtilZ.C_RegExHelper.CheckRegEx(), and Co0nUtilZ.C_RegExHelper.RegExFilterisGood().
Referenced by Co0nUtilZ.C_FTPClient.GetFileListByRegex().
RegExFilterisGood()
bool Co0nUtilZ.C_RegExHelper.RegExFilterisGood (String RegexFilter)
Testet ob ein RegEx-Filter gültig ist
Parameters
RegexFilter Filterstring
Returns
Wenn gültig wird TRUE zurückgegeben, sonst FALSE
Definition at line 72 of file C_RegExHelper.cs.
Referenced by Co0nUtilZ.C_RegExHelper.CheckRegEx(), and Co0nUtilZ.C_RegExHelper.FilterStringListByRegex().
SplitString()
List<String> Co0nUtilZ.C_RegExHelper.SplitString (String str, int chunks)
Definition at line 23 of file C_RegExHelper.cs.
Referenced by Co0nUtilZ.C_LoggingHelper.Log().
The documentation for this class was generated from the following file:
Co0nUtilZ/C_RegExHelper.cs