coonutils: Co0nUtilZ.C_CIFSClient Class Reference
Co0nUtilZ.C_CIFSClient Class Reference
This Class grants Access to a Samba/CIFS-Share Created: 08/2017 Author: D. Marx Project: https://github.com/derco0n/coonutils License: GPLv2 - Means, this is free software which comes without any warranty but can be used, modified and redistributed free of charge You should have received a copy of that license: If not look here: https://www.gnu.org/licenses/gpl-2.0.de.html
Public Member Functions
delegate void CompleteEventhandler ()
delegate void MultiLoadProgressEventHandler (object sender, ProgressEventArgs Args)
delegate void ErrorEventHandler (object sender, ErrorEventArgs Fehler)
C_CIFSClient (String Server, String User, String Password, String Domain, String Authtype="Digest")
Constructor
DirectoryInfo getFolderInfo (String Subdir)
Return the Folderinformation of a Subfolder
List< DirectoryInfo > listFolders (String Subdir, bool isLocaldir=false)
Gets all folders of a given subfolder
List< FileInfo > listFiles (String Subdir, bool isLocaldir=false)
Determines all Files of a Folder
KeyValuePair< String, DateTime > youngestFile (String Subdir, bool isLocalDir)
Determines the youngest file (last writetime) of a folder
bool isYoungestFile (String Subdir, String Filename, bool isLocalDir=false)
Checks if a file is the youngest in the specified folder
bool TestConnection (String Subdir)
Checks if a connection to the destination folder is possible </ summary>
Parameters
Subdir subfolder on server </ param>
Returns
If the folder exists (and access is possible), TRUE is returned. </ returns>
System.Threading.Thread CopyMultipleFilesFromCIFS (List< FileInfo > Files, DirectoryInfo Targetfolder, bool renameyoungest=false, String renameTo="", bool overwrite=true)
Creates a thread that downloads the file list bit by bit from a CIFS share </ summary>
Parameters
Files list of source files </ param>
Parameters
Targetfolder destination folder </ param>
Parameters
renameyoungest Save the most recent file as an additional rename copy </ param>
Parameters
renameTo New name for the renamed copy </ param>
Parameters
overwrite Overwrite existing files. </ param>
Returns
</ returns>
bool CopyFileFromCIFS (FileInfo File, DirectoryInfo Targetfolder, String renameto="", bool overwrite=true)
Kopiert eine Datei aus einer CIFS-Freigabe
System.Threading.Thread MoveMultipleFilesFromCIFS (List< FileInfo > Files, DirectoryInfo Targetfolder, bool renameyoungest=false, String renameTo="", bool overwrite=true)
Verschiebt mehrere Dateien einer CIFS-Freigabe in einen lokalen ordner
bool MoveFileFromCIFS (FileInfo File, DirectoryInfo Targetfolder, String TargetFilename="", bool overwrite=true)
Verschiebt eine Datei aus einer Netzwerkfreigabe in einen lokalen Ordner
System.Threading.Thread CopyMultipleFilesToCIFS (List< FileInfo > Files, DirectoryInfo Targetfolder, bool renameyoungest=false, String renameTo="", bool overwrite=true)
Erzeugt einen Thread welcher, die Dateiliste nach und nach in eine CIFS-Freigabe hochlädt
bool CopyFileToCIFS (FileInfo File, DirectoryInfo Targetfolder, String renameto="", bool overwrite=true)
Kopiert eine Datei aus einer CIFS-Freigabe
System.Threading.Thread MoveMultipleFilesToCIFS (List< FileInfo > Files, DirectoryInfo Targetfolder, bool renameyoungest=false, String renameTo="", bool overwrite=true)
Verschiebt mehrere Dateien von einem lokalen Ordner in eine CIFS-Freigabe
bool MoveFileToCIFS (FileInfo File, DirectoryInfo Targetfolder, String TargetFilename="", bool overwrite=true)
Verschiebt eine Datei aus einem lokalen Ordner in eine Netzwerkfreigabe
Static Public Attributes
static String AUTHTYPE_DIGEST = "Digest"
static String AUTHTYPE_BASIC = "Basic"
Events
MultiLoadProgressEventHandler CopyProgressChanged
CompleteEventhandler CopyProgressComplete
MultiLoadProgressEventHandler MoveProgressChanged
CompleteEventhandler MoveProgressComplete
ErrorEventHandler FileTransferError
ErrorEventHandler GeneralError
Detailed Description
This Class grants Access to a Samba/CIFS-Share Created: 08/2017 Author: D. Marx Project: https://github.com/derco0n/coonutils License: GPLv2 - Means, this is free software which comes without any warranty but can be used, modified and redistributed free of charge You should have received a copy of that license: If not look here: https://www.gnu.org/licenses/gpl-2.0.de.html
Definition at line 22 of file C_CIFSClient.cs.
Constructor & Destructor Documentation
C_CIFSClient()
Co0nUtilZ.C_CIFSClient.C_CIFSClient (String Server, String User, String Password, String Domain, String Authtype = "Digest")
Constructor
Parameters
Server \Servername or IP</Servername>
User Username
Password Password
Domain Domainname
Authtype
Definition at line 78 of file C_CIFSClient.cs.
References Co0nUtilZ.Domain, Co0nUtilZ.C_CIFSClient.GeneralError, and Co0nUtilZ.Server.
Member Function Documentation
CompleteEventhandler()
delegate void Co0nUtilZ.C_CIFSClient.CompleteEventhandler ()
CopyFileFromCIFS()
bool Co0nUtilZ.C_CIFSClient.CopyFileFromCIFS (FileInfo File, DirectoryInfo Targetfolder, String renameto = "", bool overwrite = true)
Kopiert eine Datei aus einer CIFS-Freigabe
Parameters
File Quelldatei
Targetfolder Zielordner
renameto Zieldatei zusätlich unter folgendem Namen speichern
overwrite Etwaige vorhandene Datei überschreiben
Returns
Gibt bei Erfolg TRUE zurück
Definition at line 627 of file C_CIFSClient.cs.
References Co0nUtilZ.C_NetworkConnection.Connect(), Co0nUtilZ.C_CIFSClient.FileTransferError, and Co0nUtilZ.C_NetworkConnection.NetworkError.
Referenced by Co0nUtilZ.C_CIFSClient.MoveMultipleFilesFromCIFS(), and Co0nUtilZ.C_CIFSClient.TestConnection().
CopyFileToCIFS()
bool Co0nUtilZ.C_CIFSClient.CopyFileToCIFS (FileInfo File, DirectoryInfo Targetfolder, String renameto = "", bool overwrite = true)
Kopiert eine Datei aus einer CIFS-Freigabe
Parameters
File Quelldatei
Targetfolder Zielordner
renameto Zieldatei zusätlich unter folgendem Namen speichern
overwrite Etwaige vorhandene Datei überschreiben
Returns
Gibt bei Erfolg TRUE zurück
Definition at line 985 of file C_CIFSClient.cs.
References Co0nUtilZ.C_NetworkConnection.Connect(), Co0nUtilZ.C_CIFSClient.FileTransferError, and Co0nUtilZ.C_NetworkConnection.NetworkError.
Referenced by Co0nUtilZ.C_CIFSClient.MoveFileFromCIFS().
CopyMultipleFilesFromCIFS()
System.Threading.Thread Co0nUtilZ.C_CIFSClient.CopyMultipleFilesFromCIFS (List< FileInfo > Files, DirectoryInfo Targetfolder, bool renameyoungest = false, String renameTo = "", bool overwrite = true)
Creates a thread that downloads the file list bit by bit from a CIFS share </ summary>
Parameters
Files list of source files </ param>
Parameters
Targetfolder destination folder </ param>
Parameters
renameyoungest Save the most recent file as an additional rename copy </ param>
Parameters
renameTo New name for the renamed copy </ param>
Parameters
overwrite Overwrite existing files. </ param>
Returns
</ returns>
Definition at line 540 of file C_CIFSClient.cs.
Referenced by Co0nUtilZ.C_CIFSClient.TestConnection().
CopyMultipleFilesToCIFS()
System.Threading.Thread Co0nUtilZ.C_CIFSClient.CopyMultipleFilesToCIFS (List< FileInfo > Files, DirectoryInfo Targetfolder, bool renameyoungest = false, String renameTo = "", bool overwrite = true)
Erzeugt einen Thread welcher, die Dateiliste nach und nach in eine CIFS-Freigabe hochlädt
Parameters
Files Liste mit Quelldateien
Targetfolder Zielordner
renameyoungest Die jüngste Datei als zusätzlich umbennante Kopie speichern
renameTo Neue Bezeichnung für die umbenannte Kopie
overwrite Existierende Dateien überschreiben.
Returns
Definition at line 898 of file C_CIFSClient.cs.
Referenced by Co0nUtilZ.C_CIFSClient.MoveFileFromCIFS().
ErrorEventHandler()
delegate void Co0nUtilZ.C_CIFSClient.ErrorEventHandler (object sender, ErrorEventArgs Fehler)
getFolderInfo()
DirectoryInfo Co0nUtilZ.C_CIFSClient.getFolderInfo (String Subdir)
Return the Folderinformation of a Subfolder
Parameters
Subdir Path on the server (everything after "\\Server\")
Returns
List with all containing subfolders
Definition at line 117 of file C_CIFSClient.cs.
References Co0nUtilZ.C_NetworkConnection.Connect(), Co0nUtilZ.C_CIFSClient.GeneralError, and Co0nUtilZ.C_NetworkConnection.NetworkError.
isYoungestFile()
bool Co0nUtilZ.C_CIFSClient.isYoungestFile (String Subdir, String Filename, bool isLocalDir = false)
Checks if a file is the youngest in the specified folder
Parameters
Subdir Path on the server (everything to "\\ server \") </ param>
Parameters
filename filename </ param>
Returns
Returns TRUE if true, otherwise FALSE </ returns>
Definition at line 409 of file C_CIFSClient.cs.
References Co0nUtilZ.C_NetworkConnection.Connect(), Co0nUtilZ.C_CIFSClient.GeneralError, Co0nUtilZ.C_NetworkConnection.NetworkError, and Co0nUtilZ.C_CIFSClient.youngestFile().
Referenced by Co0nUtilZ.C_CIFSClient.MoveFileFromCIFS(), Co0nUtilZ.C_CIFSClient.MoveMultipleFilesFromCIFS(), Co0nUtilZ.C_CIFSClient.MoveMultipleFilesToCIFS(), and Co0nUtilZ.C_CIFSClient.TestConnection().
listFiles()
List<FileInfo> Co0nUtilZ.C_CIFSClient.listFiles (String Subdir, bool isLocaldir = false)
Determines all Files of a Folder
Parameters
Subdir Serverpath (everything after "\\Server\")
Returns
List with all files of that folder
Definition at line 218 of file C_CIFSClient.cs.
References Co0nUtilZ.C_NetworkConnection.Connect(), Co0nUtilZ.Directory, Co0nUtilZ.C_CIFSClient.GeneralError, and Co0nUtilZ.C_NetworkConnection.NetworkError.
Referenced by Co0nUtilZ.C_CIFSClient.youngestFile().
listFolders()
List<DirectoryInfo> Co0nUtilZ.C_CIFSClient.listFolders (String Subdir, bool isLocaldir = false)
Gets all folders of a given subfolder
Parameters
Subdir Serverpath (everything after "\\Server\")
Returns
List With all subfolders
Definition at line 158 of file C_CIFSClient.cs.
References Co0nUtilZ.C_NetworkConnection.Connect(), Co0nUtilZ.Directory, Co0nUtilZ.C_CIFSClient.GeneralError, and Co0nUtilZ.C_NetworkConnection.NetworkError.
MoveFileFromCIFS()
bool Co0nUtilZ.C_CIFSClient.MoveFileFromCIFS (FileInfo File, DirectoryInfo Targetfolder, String TargetFilename = "", bool overwrite = true)
Verschiebt eine Datei aus einer Netzwerkfreigabe in einen lokalen Ordner
Parameters
File Quelldatei
Targetfolder Zielordner
TargetFilename Zieldateiname
overwrite Vorhandene Datei überschreiben?
Returns
Definition at line 802 of file C_CIFSClient.cs.
References Co0nUtilZ.C_NetworkConnection.Connect(), Co0nUtilZ.C_CIFSClient.CopyFileToCIFS(), Co0nUtilZ.C_CIFSClient.CopyMultipleFilesToCIFS(), Co0nUtilZ.C_CIFSClient.CopyProgressChanged, Co0nUtilZ.C_CIFSClient.CopyProgressComplete, Co0nUtilZ.C_CIFSClient.FileTransferError, Co0nUtilZ.C_CIFSClient.isYoungestFile(), and Co0nUtilZ.C_NetworkConnection.NetworkError.
Referenced by Co0nUtilZ.C_CIFSClient.MoveMultipleFilesFromCIFS().
MoveFileToCIFS()
bool Co0nUtilZ.C_CIFSClient.MoveFileToCIFS (FileInfo File, DirectoryInfo Targetfolder, String TargetFilename = "", bool overwrite = true)
Verschiebt eine Datei aus einem lokalen Ordner in eine Netzwerkfreigabe
Parameters
File Quelldatei
Targetfolder Zielordner
TargetFilename Zieldateiname
overwrite Vorhandene Datei überschreiben?
Returns
Definition at line 1168 of file C_CIFSClient.cs.
References Co0nUtilZ.C_NetworkConnection.Connect(), Co0nUtilZ.C_CIFSClient.FileTransferError, and Co0nUtilZ.C_NetworkConnection.NetworkError.
Referenced by Co0nUtilZ.C_CIFSClient.MoveMultipleFilesToCIFS().
MoveMultipleFilesFromCIFS()
System.Threading.Thread Co0nUtilZ.C_CIFSClient.MoveMultipleFilesFromCIFS (List< FileInfo > Files, DirectoryInfo Targetfolder, bool renameyoungest = false, String renameTo = "", bool overwrite = true)
Verschiebt mehrere Dateien einer CIFS-Freigabe in einen lokalen ordner
Parameters
Files Quelldateien
Targetfolder Zielordner
renameyoungest jüngste Datei umbennen?
renameTo Neuer Name für umbenannte Datei
overwrite Vorhandene Dateien überschreiben?
Returns
Definition at line 719 of file C_CIFSClient.cs.
References Co0nUtilZ.C_CIFSClient.CopyFileFromCIFS(), Co0nUtilZ.C_CIFSClient.isYoungestFile(), Co0nUtilZ.C_CIFSClient.MoveFileFromCIFS(), Co0nUtilZ.C_CIFSClient.MoveProgressChanged, and Co0nUtilZ.C_CIFSClient.MoveProgressComplete.
MoveMultipleFilesToCIFS()
System.Threading.Thread Co0nUtilZ.C_CIFSClient.MoveMultipleFilesToCIFS (List< FileInfo > Files, DirectoryInfo Targetfolder, bool renameyoungest = false, String renameTo = "", bool overwrite = true)
Verschiebt mehrere Dateien von einem lokalen Ordner in eine CIFS-Freigabe
Parameters
Files Quelldateien
Targetfolder Zielordner
renameyoungest jüngste Datei umbennen?
renameTo Neuer Name für umbenannte Datei
overwrite Vorhandene Dateien überschreiben?
Returns
Definition at line 1079 of file C_CIFSClient.cs.
References Co0nUtilZ.C_CIFSClient.isYoungestFile(), Co0nUtilZ.C_CIFSClient.MoveFileToCIFS(), Co0nUtilZ.C_CIFSClient.MoveProgressChanged, and Co0nUtilZ.C_CIFSClient.MoveProgressComplete.
MultiLoadProgressEventHandler()
delegate void Co0nUtilZ.C_CIFSClient.MultiLoadProgressEventHandler (object sender, ProgressEventArgs Args)
TestConnection()
bool Co0nUtilZ.C_CIFSClient.TestConnection (String Subdir)
Checks if a connection to the destination folder is possible </ summary>
Parameters
Subdir subfolder on server </ param>
Returns
If the folder exists (and access is possible), TRUE is returned. </ returns>
Definition at line 478 of file C_CIFSClient.cs.
References Co0nUtilZ.C_NetworkConnection.Connect(), Co0nUtilZ.C_CIFSClient.CopyFileFromCIFS(), Co0nUtilZ.C_CIFSClient.CopyMultipleFilesFromCIFS(), Co0nUtilZ.C_CIFSClient.CopyProgressChanged, Co0nUtilZ.C_CIFSClient.CopyProgressComplete, Co0nUtilZ.File, Co0nUtilZ.C_CIFSClient.GeneralError, Co0nUtilZ.C_CIFSClient.isYoungestFile(), and Co0nUtilZ.C_NetworkConnection.NetworkError.
youngestFile()
KeyValuePair<String, DateTime> Co0nUtilZ.C_CIFSClient.youngestFile (String Subdir, bool isLocalDir)
Determines the youngest file (last writetime) of a folder
Parameters
Subdir Serverpath (everything after "\\Server\")
Returns
KeyValuePair of the youngest file
Definition at line 299 of file C_CIFSClient.cs.
References Co0nUtilZ.C_NetworkConnection.Connect(), Co0nUtilZ.File, Co0nUtilZ.C_CIFSClient.GeneralError, Co0nUtilZ.C_CIFSClient.listFiles(), and Co0nUtilZ.C_NetworkConnection.NetworkError.
Referenced by Co0nUtilZ.C_CIFSClient.isYoungestFile().
Member Data Documentation
AUTHTYPE_BASIC
String Co0nUtilZ.C_CIFSClient.AUTHTYPE_BASIC = "Basic" static
Definition at line 25 of file C_CIFSClient.cs.
AUTHTYPE_DIGEST
String Co0nUtilZ.C_CIFSClient.AUTHTYPE_DIGEST = "Digest" static
Definition at line 24 of file C_CIFSClient.cs.
Event Documentation
CopyProgressChanged
MultiLoadProgressEventHandler Co0nUtilZ.C_CIFSClient.CopyProgressChanged
Definition at line 46 of file C_CIFSClient.cs.
Referenced by Co0nUtilZ.C_CIFSClient.MoveFileFromCIFS(), and Co0nUtilZ.C_CIFSClient.TestConnection().
CopyProgressComplete
CompleteEventhandler Co0nUtilZ.C_CIFSClient.CopyProgressComplete
Definition at line 47 of file C_CIFSClient.cs.
Referenced by Co0nUtilZ.C_CIFSClient.MoveFileFromCIFS(), and Co0nUtilZ.C_CIFSClient.TestConnection().
FileTransferError
ErrorEventHandler Co0nUtilZ.C_CIFSClient.FileTransferError
Definition at line 50 of file C_CIFSClient.cs.
Referenced by Co0nUtilZ.C_CIFSClient.CopyFileFromCIFS(), Co0nUtilZ.C_CIFSClient.CopyFileToCIFS(), Co0nUtilZ.C_CIFSClient.MoveFileFromCIFS(), and Co0nUtilZ.C_CIFSClient.MoveFileToCIFS().
GeneralError
ErrorEventHandler Co0nUtilZ.C_CIFSClient.GeneralError
Definition at line 51 of file C_CIFSClient.cs.
Referenced by Co0nUtilZ.C_CIFSClient.C_CIFSClient(), Co0nUtilZ.C_CIFSClient.getFolderInfo(), Co0nUtilZ.C_CIFSClient.isYoungestFile(), Co0nUtilZ.C_CIFSClient.listFiles(), Co0nUtilZ.C_CIFSClient.listFolders(), Co0nUtilZ.C_CIFSClient.TestConnection(), and Co0nUtilZ.C_CIFSClient.youngestFile().
MoveProgressChanged
MultiLoadProgressEventHandler Co0nUtilZ.C_CIFSClient.MoveProgressChanged
Definition at line 48 of file C_CIFSClient.cs.
Referenced by Co0nUtilZ.C_CIFSClient.MoveMultipleFilesFromCIFS(), and Co0nUtilZ.C_CIFSClient.MoveMultipleFilesToCIFS().
MoveProgressComplete
CompleteEventhandler Co0nUtilZ.C_CIFSClient.MoveProgressComplete
Definition at line 49 of file C_CIFSClient.cs.
Referenced by Co0nUtilZ.C_CIFSClient.MoveMultipleFilesFromCIFS(), and Co0nUtilZ.C_CIFSClient.MoveMultipleFilesToCIFS().
The documentation for this class was generated from the following file:
Co0nUtilZ/C_CIFSClient.cs