coonutils: Co0nUtilZ.C_RegistryHelper Class Reference
Co0nUtilZ.C_RegistryHelper Class Reference
This is a helper class which manages to read from and write to windows registry Created: 06/2017 Author: D. Marx Project: https://github.com/derco0n/coonutils License: GPLv2 - Means, this is free software which comes without any warranty but can be used, modified and redistributed free of charge You should have received a copy of that license: If not look here: https://www.gnu.org/licenses/gpl-2.0.de.html
Public Member Functions
delegate void ErrorEventHandler (object sender, ErrorEventArgs Fehler)
C_RegistryHelper (RegistryKey Rootkey, String Subkey)
List< String > ListValues (String SubKey="")
Ermittelt alle Wertenamen eines Unterschlüssels
bool hasInstances ()
Ermittelt ob eine es unter dem Angebenen Schlüssel bereits Instanzen (Unterschlüssel) gibt.
String ReadSettingFromRegistry (String Instancename, String valuename)
Liest einen Wert auf einem Wertefeld aus
bool WriteSettingToRegistry (String Instancename, String valuename, String value)
Schreibt einen Wert in die Registry
bool dropInstance (String Instancename)
Löscht eine komplette Instanz (Unterschlüssel des aktuellen Registry-Schlüssels)
bool dropValue (String Instancename, String valuename)
Löscht einen Wert in einem Instanzunterschlüssel
List< String > getInstances ()
//Listet alle Instanzen (Unterschlüssel des aktuellen Schlüsseln) auf
Properties
RegistryKey rootkey [get]
String subkey [get]
Events
ErrorEventHandler GeneralError
Detailed Description
This is a helper class which manages to read from and write to windows registry Created: 06/2017 Author: D. Marx Project: https://github.com/derco0n/coonutils License: GPLv2 - Means, this is free software which comes without any warranty but can be used, modified and redistributed free of charge You should have received a copy of that license: If not look here: https://www.gnu.org/licenses/gpl-2.0.de.html
Definition at line 20 of file C_RegistryHelper.cs.
Constructor & Destructor Documentation
C_RegistryHelper()
Co0nUtilZ.C_RegistryHelper.C_RegistryHelper (RegistryKey Rootkey, String Subkey)
Definition at line 52 of file C_RegistryHelper.cs.
Member Function Documentation
dropInstance()
bool Co0nUtilZ.C_RegistryHelper.dropInstance (String Instancename)
Löscht eine komplette Instanz (Unterschlüssel des aktuellen Registry-Schlüssels)
Parameters
Instancename Instanzname (Unterschlüssel des aktuellen Registry-Schlüssels)
Returns
Gibt bei Erfolg TRUE zurück.
Definition at line 190 of file C_RegistryHelper.cs.
References Co0nUtilZ.C_RegistryHelper.GeneralError.
Referenced by Co0nUtilZ.C_BasicSettingsTemplate.DeleteInstance(), and Co0nUtilZ.C_BasicSettingsTemplate.renameInstance().
dropValue()
bool Co0nUtilZ.C_RegistryHelper.dropValue (String Instancename, String valuename)
Löscht einen Wert in einem Instanzunterschlüssel
Parameters
Instancename Instanzname (Unterschlüssel des aktuellen Registry-Schlüssels)
valuename Name des zu löschenden Felds
Returns
Gibt bei Erfolg TRUE zurück.
Definition at line 217 of file C_RegistryHelper.cs.
References Co0nUtilZ.C_RegistryHelper.GeneralError.
Referenced by Co0nUtilZ.C_BasicSettingsTemplate.DeleteValue().
ErrorEventHandler()
delegate void Co0nUtilZ.C_RegistryHelper.ErrorEventHandler (object sender, ErrorEventArgs Fehler)
getInstances()
List<String> Co0nUtilZ.C_RegistryHelper.getInstances ()
//Listet alle Instanzen (Unterschlüssel des aktuellen Schlüsseln) auf
Returns
Gibt eine Liste mit gefundenen Instanznamen zurück
Definition at line 267 of file C_RegistryHelper.cs.
References Co0nUtilZ.C_RegistryHelper.GeneralError, and Co0nUtilZ.C_RegistryHelper.rootkey.
hasInstances()
bool Co0nUtilZ.C_RegistryHelper.hasInstances ()
Ermittelt ob eine es unter dem Angebenen Schlüssel bereits Instanzen (Unterschlüssel) gibt.
Returns
Wenn Instanzen (Unterschlüssel) vorhanden sind, wird TRUE zurückgegeben.
Definition at line 111 of file C_RegistryHelper.cs.
References Co0nUtilZ.C_RegistryHelper.rootkey.
ListValues()
List<String> Co0nUtilZ.C_RegistryHelper.ListValues (String SubKey = "")
Ermittelt alle Wertenamen eines Unterschlüssels
Parameters
SubKey Unterschlüsssel
Returns
Gibt alle gefundenen Wertenamen zurück.
Definition at line 67 of file C_RegistryHelper.cs.
Referenced by Co0nUtilZ.C_BasicSettingsTemplate.readSettingsFromRegistry(), and Co0nUtilZ.C_BasicSettingsTemplate.writeAllSettingsToRegistry().
ReadSettingFromRegistry()
String Co0nUtilZ.C_RegistryHelper.ReadSettingFromRegistry (String Instancename, String valuename)
Liest einen Wert auf einem Wertefeld aus
Parameters
Instancename Instanzname (Unterschlüssel des aktuellen Registry-Schlüssels)
valuename Name des auszulesenden Werts
Returns
Gibt bei Erfolg den Wert des angegebenen Felds zurück. Im Fehlerfall wird ein leerer String zurück gegeben
Definition at line 140 of file C_RegistryHelper.cs.
Referenced by Co0nUtilZ.C_BasicSettingsTemplate.readOneSettingFromRegistry(), and Co0nUtilZ.C_BasicSettingsTemplate.readSettingsFromRegistry().
WriteSettingToRegistry()
bool Co0nUtilZ.C_RegistryHelper.WriteSettingToRegistry (String Instancename, String valuename, String value)
Schreibt einen Wert in die Registry
Parameters
Instancename Instanzname (Unterschlüssel des aktuellen Registry-Schlüssels)
valuename Name des zu schreibenden Felds
value Wert
Returns
Gibt bei Erfolg TRUE zurück.
Definition at line 161 of file C_RegistryHelper.cs.
References Co0nUtilZ.C_RegistryHelper.GeneralError.
Referenced by Co0nUtilZ.C_BasicSettingsTemplate.writeSettingToRegistry().
Property Documentation
rootkey
RegistryKey Co0nUtilZ.C_RegistryHelper.rootkey get
Definition at line 34 of file C_RegistryHelper.cs.
Referenced by Co0nUtilZ.C_RegistryHelper.getInstances(), and Co0nUtilZ.C_RegistryHelper.hasInstances().
subkey
String Co0nUtilZ.C_RegistryHelper.subkey get
Definition at line 42 of file C_RegistryHelper.cs.
Event Documentation
GeneralError
ErrorEventHandler Co0nUtilZ.C_RegistryHelper.GeneralError
Definition at line 28 of file C_RegistryHelper.cs.
Referenced by Co0nUtilZ.C_RegistryHelper.dropInstance(), Co0nUtilZ.C_RegistryHelper.dropValue(), Co0nUtilZ.C_RegistryHelper.getInstances(), and Co0nUtilZ.C_RegistryHelper.WriteSettingToRegistry().
The documentation for this class was generated from the following file:
Co0nUtilZ/C_RegistryHelper.cs