coonutils: Co0nUtilZ.C_NetClient Class Reference
Co0nUtilZ.C_NetClient Class Reference
This class represents a TCP-Client Author: D. Marx Project: https://github.com/derco0n/coonutils License: GPLv2 - Means, this is free software which comes without any warranty but can be used, modified and redistributed free of charge You should have received a copy of that license: If not look here: https://www.gnu.org/licenses/gpl-2.0.de.html
Public Member Functions
delegate void ProgressEventHandler (object sender, Co0nUtilZ.ProgressEventArgs Args)
delegate void ErrorEventHandler (object sender, Co0nUtilZ.ErrorEventArgs Args)
C_NetClient (String Host, int port)
Konstruktor
void ConnectToServer ()
Stellt eine Asynchrone-Verbindung mit dem angegebenen Server her
bool ConIsAlive (Socket socket)
Prüft ob eine Verbindung noch aktiv ist
void Disconnect ()
Verbindung zum Server trennen
void SendData (String Message)
Sendet einen String (Asynchron) an den Server
Static Public Member Functions
static String IPbyHostname (String Hostname)
Löst einen Hostnamen in eine IP auf
Properties
int ConnectTimeout [get, set]
bool IsConnected [get]
Events
ProgressEventHandler DataReceived
ProgressEventHandler DataSent
ProgressEventHandler Connected
ProgressEventHandler Disconnected
ErrorEventHandler OnError
Detailed Description
This class represents a TCP-Client Author: D. Marx Project: https://github.com/derco0n/coonutils License: GPLv2 - Means, this is free software which comes without any warranty but can be used, modified and redistributed free of charge You should have received a copy of that license: If not look here: https://www.gnu.org/licenses/gpl-2.0.de.html
Definition at line 23 of file C_NetClient.cs.
Constructor & Destructor Documentation
C_NetClient()
Co0nUtilZ.C_NetClient.C_NetClient (String Host, int port)
Konstruktor
Parameters
Host Zielhost
port Zielport
Definition at line 95 of file C_NetClient.cs.
References Co0nUtilZ.C_NetClient.IPbyHostname().
Member Function Documentation
ConIsAlive()
bool Co0nUtilZ.C_NetClient.ConIsAlive (Socket socket)
Prüft ob eine Verbindung noch aktiv ist
Parameters
socket
Returns
Definition at line 207 of file C_NetClient.cs.
References Co0nUtilZ.C_NetClient.Disconnected.
Referenced by Co0nUtilZ.C_NetClient.SendData().
ConnectToServer()
void Co0nUtilZ.C_NetClient.ConnectToServer ()
Stellt eine Asynchrone-Verbindung mit dem angegebenen Server her
Definition at line 116 of file C_NetClient.cs.
References Co0nUtilZ.C_NetClient.OnError.
Disconnect()
void Co0nUtilZ.C_NetClient.Disconnect ()
Verbindung zum Server trennen
Definition at line 298 of file C_NetClient.cs.
References Co0nUtilZ.C_NetClient.Disconnected.
ErrorEventHandler()
delegate void Co0nUtilZ.C_NetClient.ErrorEventHandler (object sender, Co0nUtilZ.ErrorEventArgs Args)
IPbyHostname()
static String Co0nUtilZ.C_NetClient.IPbyHostname (String Hostname) static
Löst einen Hostnamen in eine IP auf
Parameters
Hostname
Returns
Definition at line 51 of file C_NetClient.cs.
References Co0nUtilZ.C_NetClient.ConnectTimeout.
Referenced by Co0nUtilZ.C_NetClient.C_NetClient().
ProgressEventHandler()
delegate void Co0nUtilZ.C_NetClient.ProgressEventHandler (object sender, Co0nUtilZ.ProgressEventArgs Args)
SendData()
void Co0nUtilZ.C_NetClient.SendData (String Message)
Sendet einen String (Asynchron) an den Server
Parameters
Message
Definition at line 313 of file C_NetClient.cs.
References Co0nUtilZ.C_NetClient.ConIsAlive(), Co0nUtilZ.C_NetClient.Connected, Co0nUtilZ.C_NetClient.DataReceived, Co0nUtilZ.C_NetClient.DataSent, and Co0nUtilZ.C_NetClient.OnError.
Property Documentation
ConnectTimeout
int Co0nUtilZ.C_NetClient.ConnectTimeout get set
Definition at line 59 of file C_NetClient.cs.
Referenced by Co0nUtilZ.C_NetClient.IPbyHostname().
IsConnected
bool Co0nUtilZ.C_NetClient.IsConnected get
Definition at line 75 of file C_NetClient.cs.
Event Documentation
Connected
ProgressEventHandler Co0nUtilZ.C_NetClient.Connected
Definition at line 39 of file C_NetClient.cs.
Referenced by Co0nUtilZ.C_NetClient.SendData().
DataReceived
ProgressEventHandler Co0nUtilZ.C_NetClient.DataReceived
Definition at line 37 of file C_NetClient.cs.
Referenced by Co0nUtilZ.C_NetClient.SendData().
DataSent
ProgressEventHandler Co0nUtilZ.C_NetClient.DataSent
Definition at line 38 of file C_NetClient.cs.
Referenced by Co0nUtilZ.C_NetClient.SendData().
Disconnected
ProgressEventHandler Co0nUtilZ.C_NetClient.Disconnected
Definition at line 40 of file C_NetClient.cs.
Referenced by Co0nUtilZ.C_NetClient.ConIsAlive(), and Co0nUtilZ.C_NetClient.Disconnect().
OnError
ErrorEventHandler Co0nUtilZ.C_NetClient.OnError
Definition at line 42 of file C_NetClient.cs.
Referenced by Co0nUtilZ.C_NetClient.ConnectToServer(), and Co0nUtilZ.C_NetClient.SendData().
The documentation for this class was generated from the following file:
Co0nUtilZ/C_NetClient.cs