coonutils: Co0nUtilZ.C_BasicSettingsTemplate Class Reference
Co0nUtilZ.C_BasicSettingsTemplate Class Reference
Template for Settingsclasses This abstract class will hold settings, save them to the registry and reads them from registry. Author: D. Marx Project: https://github.com/derco0n/coonutils License: GPLv2 - Means, this is free software which comes without any warranty but can be used, modified and redistributed free of charge You should have received a copy of that license: If not look here: https://www.gnu.org/licenses/gpl-2.0.de.html
Public Member Functions
C_BasicSettingsTemplate (RegistryKey Rootkey, String Subkey, String instancename)
delegate void CompleteEventhandler ()
delegate void SettingChangedHandler (ProgressEventArgs e)
delegate void ErrorEventHandler (object sender, ErrorEventArgs Fehler)
virtual void runJob ()
Override this method to run a self defined job with current settings
virtual void readSettingsFromRegistry ()
Override this method to read settings from registry
bool writeSettingToRegistry (String valuename, String value)
Writes one setting to Registry
bool DeleteInstance ()
deletes the complete jobinstance from registry.
bool DeleteValue (String valuename)
Deletes a value of the current instance from the registry...
Protected Member Functions
virtual void OnSettingChanged (ProgressEventArgs e)
virtual void OnJobCompleted ()
virtual void OnErrorOccured (object sender, ErrorEventArgs e)
String readOneSettingFromRegistry (String Setting)
virtual bool writeAllSettingsToRegistry ()
Override this Method to Write all your Settings to the registry
virtual bool renameInstance (String newName)
Override this to rename this instance in the registry
Protected Attributes
C_RegistryHelper myRegHelper
String _instancename
const String _StartSearchString = "Start"
String [] _Starttimes
Properties
String [] Starttimes [get, set]
List with daily Start-Times
RegistryKey Rootkey [get]
String SubKey [get]
virtual String Instancename [get, set]
String [] StartHours [get]
returns the hour-part of starttimes
String [] StartMinutes [get]
returns the minute-part of starttimes
Events
CompleteEventhandler JobCompleted
SettingChangedHandler SettingChanged
ErrorEventHandler ErrorOccured
Detailed Description
Template for Settingsclasses This abstract class will hold settings, save them to the registry and reads them from registry. Author: D. Marx Project: https://github.com/derco0n/coonutils License: GPLv2 - Means, this is free software which comes without any warranty but can be used, modified and redistributed free of charge You should have received a copy of that license: If not look here: https://www.gnu.org/licenses/gpl-2.0.de.html
Definition at line 19 of file C_BasicSettingsTemplate.cs.
Constructor & Destructor Documentation
C_BasicSettingsTemplate()
Co0nUtilZ.C_BasicSettingsTemplate.C_BasicSettingsTemplate (RegistryKey Rootkey, String Subkey, String instancename)
Definition at line 29 of file C_BasicSettingsTemplate.cs.
References Co0nUtilZ.C_BasicSettingsTemplate.Starttimes.
Member Function Documentation
CompleteEventhandler()
delegate void Co0nUtilZ.C_BasicSettingsTemplate.CompleteEventhandler ()
DeleteInstance()
bool Co0nUtilZ.C_BasicSettingsTemplate.DeleteInstance ()
deletes the complete jobinstance from registry.
Returns
TRUE if success
Definition at line 343 of file C_BasicSettingsTemplate.cs.
References Co0nUtilZ.C_RegistryHelper.dropInstance().
DeleteValue()
bool Co0nUtilZ.C_BasicSettingsTemplate.DeleteValue (String valuename)
Deletes a value of the current instance from the registry...
Returns
TRUE if success
Definition at line 352 of file C_BasicSettingsTemplate.cs.
References Co0nUtilZ.C_RegistryHelper.dropValue().
Referenced by Co0nUtilZ.C_BasicSettingsTemplate.writeAllSettingsToRegistry().
ErrorEventHandler()
delegate void Co0nUtilZ.C_BasicSettingsTemplate.ErrorEventHandler (object sender, ErrorEventArgs Fehler)
OnErrorOccured()
virtual void Co0nUtilZ.C_BasicSettingsTemplate.OnErrorOccured (object sender, ErrorEventArgs e) protected virtual
Definition at line 173 of file C_BasicSettingsTemplate.cs.
References Co0nUtilZ.C_BasicSettingsTemplate.ErrorOccured, and Co0nUtilZ.C_BasicSettingsTemplate.runJob().
Referenced by Co0nUtilZ.C_BasicSettingsTemplate.readSettingsFromRegistry().
OnJobCompleted()
virtual void Co0nUtilZ.C_BasicSettingsTemplate.OnJobCompleted () protected virtual
Definition at line 161 of file C_BasicSettingsTemplate.cs.
References Co0nUtilZ.C_BasicSettingsTemplate.JobCompleted.
OnSettingChanged()
virtual void Co0nUtilZ.C_BasicSettingsTemplate.OnSettingChanged (ProgressEventArgs e) protected virtual
Definition at line 149 of file C_BasicSettingsTemplate.cs.
References Co0nUtilZ.C_BasicSettingsTemplate.SettingChanged.
readOneSettingFromRegistry()
String Co0nUtilZ.C_BasicSettingsTemplate.readOneSettingFromRegistry (String Setting) protected
Definition at line 228 of file C_BasicSettingsTemplate.cs.
References Co0nUtilZ.C_RegistryHelper.ReadSettingFromRegistry().
readSettingsFromRegistry()
virtual void Co0nUtilZ.C_BasicSettingsTemplate.readSettingsFromRegistry () virtual
Override this method to read settings from registry
Definition at line 199 of file C_BasicSettingsTemplate.cs.
References Co0nUtilZ.C_RegistryHelper.ListValues(), Co0nUtilZ.C_BasicSettingsTemplate.OnErrorOccured(), and Co0nUtilZ.C_RegistryHelper.ReadSettingFromRegistry().
renameInstance()
virtual bool Co0nUtilZ.C_BasicSettingsTemplate.renameInstance (String newName) protected virtual
Override this to rename this instance in the registry
Parameters
newName new Name
Definition at line 321 of file C_BasicSettingsTemplate.cs.
References Co0nUtilZ.C_BasicSettingsTemplate._instancename, Co0nUtilZ.C_RegistryHelper.dropInstance(), and Co0nUtilZ.C_BasicSettingsTemplate.writeAllSettingsToRegistry().
runJob()
virtual void Co0nUtilZ.C_BasicSettingsTemplate.runJob () virtual
Override this method to run a self defined job with current settings
Definition at line 191 of file C_BasicSettingsTemplate.cs.
Referenced by Co0nUtilZ.C_BasicSettingsTemplate.OnErrorOccured().
SettingChangedHandler()
delegate void Co0nUtilZ.C_BasicSettingsTemplate.SettingChangedHandler (ProgressEventArgs e)
writeAllSettingsToRegistry()
virtual bool Co0nUtilZ.C_BasicSettingsTemplate.writeAllSettingsToRegistry () protected virtual
Override this Method to Write all your Settings to the registry
Returns
Definition at line 237 of file C_BasicSettingsTemplate.cs.
References Co0nUtilZ.C_BasicSettingsTemplate.DeleteValue(), Co0nUtilZ.C_RegistryHelper.ListValues(), and Co0nUtilZ.C_BasicSettingsTemplate.writeSettingToRegistry().
Referenced by Co0nUtilZ.C_BasicSettingsTemplate.renameInstance().
writeSettingToRegistry()
bool Co0nUtilZ.C_BasicSettingsTemplate.writeSettingToRegistry (String valuename, String value)
Writes one setting to Registry
Parameters
valuename
value
Returns
Definition at line 311 of file C_BasicSettingsTemplate.cs.
References Co0nUtilZ.C_RegistryHelper.WriteSettingToRegistry().
Referenced by Co0nUtilZ.C_BasicSettingsTemplate.writeAllSettingsToRegistry().
Member Data Documentation
_instancename
String Co0nUtilZ.C_BasicSettingsTemplate._instancename protected
Definition at line 23 of file C_BasicSettingsTemplate.cs.
Referenced by Co0nUtilZ.C_BasicSettingsTemplate.renameInstance().
_StartSearchString
const String Co0nUtilZ.C_BasicSettingsTemplate._StartSearchString = "Start" protected
Definition at line 24 of file C_BasicSettingsTemplate.cs.
_Starttimes
String [] Co0nUtilZ.C_BasicSettingsTemplate._Starttimes protected
Definition at line 25 of file C_BasicSettingsTemplate.cs.
myRegHelper
C_RegistryHelper Co0nUtilZ.C_BasicSettingsTemplate.myRegHelper protected
Definition at line 22 of file C_BasicSettingsTemplate.cs.
Property Documentation
Instancename
virtual String Co0nUtilZ.C_BasicSettingsTemplate.Instancename get set
Definition at line 76 of file C_BasicSettingsTemplate.cs.
Rootkey
RegistryKey Co0nUtilZ.C_BasicSettingsTemplate.Rootkey get
Definition at line 60 of file C_BasicSettingsTemplate.cs.
StartHours
String [] Co0nUtilZ.C_BasicSettingsTemplate.StartHours get
returns the hour-part of starttimes
Definition at line 94 of file C_BasicSettingsTemplate.cs.
StartMinutes
String [] Co0nUtilZ.C_BasicSettingsTemplate.StartMinutes get
returns the minute-part of starttimes
Definition at line 114 of file C_BasicSettingsTemplate.cs.
Starttimes
String [] Co0nUtilZ.C_BasicSettingsTemplate.Starttimes get set
List with daily Start-Times
Definition at line 43 of file C_BasicSettingsTemplate.cs.
Referenced by Co0nUtilZ.C_BasicSettingsTemplate.C_BasicSettingsTemplate().
SubKey
String Co0nUtilZ.C_BasicSettingsTemplate.SubKey get
Definition at line 68 of file C_BasicSettingsTemplate.cs.
Event Documentation
ErrorOccured
ErrorEventHandler Co0nUtilZ.C_BasicSettingsTemplate.ErrorOccured
Definition at line 144 of file C_BasicSettingsTemplate.cs.
Referenced by Co0nUtilZ.C_BasicSettingsTemplate.OnErrorOccured().
JobCompleted
CompleteEventhandler Co0nUtilZ.C_BasicSettingsTemplate.JobCompleted
Definition at line 142 of file C_BasicSettingsTemplate.cs.
Referenced by Co0nUtilZ.C_BasicSettingsTemplate.OnJobCompleted().
SettingChanged
SettingChangedHandler Co0nUtilZ.C_BasicSettingsTemplate.SettingChanged
Definition at line 143 of file C_BasicSettingsTemplate.cs.
Referenced by Co0nUtilZ.C_BasicSettingsTemplate.OnSettingChanged().
The documentation for this class was generated from the following file:
Co0nUtilZ/C_BasicSettingsTemplate.cs